// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $portfolio from "./routes/portfolio.tsx";
import * as $services from "./routes/services.tsx";
import * as $team from "./routes/team.tsx";
import * as $Navigation from "./islands/Navigation.tsx";
import * as $animatedHeader from "./islands/animatedHeader.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/portfolio.tsx": $portfolio,
    "./routes/services.tsx": $services,
    "./routes/team.tsx": $team,
  },
  islands: {
    "./islands/Navigation.tsx": $Navigation,
    "./islands/animatedHeader.tsx": $animatedHeader,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
